USE [master]
GO

/****** Object:  Database [MAS2019]    Script Date: 4.01.2021 20:46:09 ******/
CREATE DATABASE [MAS2019]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MASBatu2019', FILENAME = N'D:\SQL Server 2017 Express Edition\MSSQL14.BATUR\MSSQL\DATA\MASBatu2019.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MASBatu2019_log', FILENAME = N'D:\SQL Server 2017 Express Edition\MSSQL14.BATUR\MSSQL\DATA\MASBatu2019_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MAS2019].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MAS2019] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MAS2019] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MAS2019] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MAS2019] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MAS2019] SET ARITHABORT OFF 
GO

ALTER DATABASE [MAS2019] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MAS2019] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MAS2019] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MAS2019] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MAS2019] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MAS2019] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MAS2019] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MAS2019] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MAS2019] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MAS2019] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MAS2019] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MAS2019] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MAS2019] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MAS2019] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MAS2019] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MAS2019] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MAS2019] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MAS2019] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MAS2019] SET  MULTI_USER 
GO

ALTER DATABASE [MAS2019] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MAS2019] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MAS2019] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MAS2019] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MAS2019] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MAS2019] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MAS2019] SET  READ_WRITE 
GO

